#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeft,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rearLeft,      tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     rearRight,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S4_C1_2,     frontRight,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S4_C2_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S4_C3_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S4_C3_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S4_C3_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S4_C3_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S4_C3_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S4_C3_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <JoystickDriver.c>

int driveEncoderCycle = 1120;
float manualDriveScale = (0.7874 * 0.7777);
float autoDriveScale = 0.7777;

int resetDriveEncoders()
{
	nMotorEncoder [frontLeft] = 0;
	nMotorEncoder [frontRight] = 0;
	nMotorEncoder [rearLeft] = 0;
	nMotorEncoder [rearRight] = 0;
	return 1;
}

void initializeRobot()
{
	bDisplayDiagnostics = false;
	if (resetDriveEncoders() == 1)
	{
		nxtDisplayCenteredTextLine(3, "Encoders");
		nxtDisplayCenteredTextLine(4, "successfully");
		nxtDisplayCenteredTextLine(5, "reset.");
		wait1Msec(1000);
	}
	eraseDisplay();
	bDisplayDiagnostics = true;
}

task main()
{
	initializeRobot();

	int x1, y1, x2;
	int threshold = 8;
	int liftPrecisionFactor;

	waitForStart();

	/*
	Encoder demo
	while (nMotorEncoder [frontLeft] < driveEncoderCycle)
	{
	motor [frontLeft] = 12 * autoDriveScale;
	}
	motor [frontLeft] = 0 * autoDriveScale;
	*/

	//run loop
	while (1)
	{
		//joystick refresh
		getJoystickSettings(joystick);

		//lift precision factor - manual control of value
		if (joy2Btn(6) == 1) {
			liftPrecisionFactor += 5;
			while (joy2Btn(6) != 0)
			{
			}
		}
		else if (joy2Btn(8) == 1) {
			liftPrecisionFactor -= 5;
			while (joy2Btn(8) != 0)
			{
			}
		}

		//lift precision factor - automatic control of bounds
		if (liftPrecisionFactor <= 0) {
			liftPrecisionFactor = 5;
		}
		else if (liftPrecisionFactor >= 100) {
			liftPrecisionFactor = 95;
		}

		//drive code
	x1 = (abs(joystick.joy1_x1) > threshold) ? joystick.joy1_x1 * manualDriveScale : 0;
	y1 = (abs(joystick.joy1_y1) > threshold) ? joystick.joy1_y1 * manualDriveScale : 0;
	x2 = (abs(joystick.joy1_x2) > threshold) ? joystick.joy1_x2 * manualDriveScale : 0;

		motor [frontLeft] = y1 + x2 + x1;
		motor [frontRight] = y1 - x2 - x1;
		motor [rearLeft] = y1 + x2 - x1;
		motor [rearRight] = y1 - x2 + x1;

		//arm control
		if (joy2Btn(5) == 1) {
			motor [lift] = 100 - liftPrecisionFactor;
		}
		else if (joy2Btn(7) == 1) {
			motor [lift] = -100 + liftPrecisionFactor;
		}
		else {
			motor [lift] = 0;
		}
		if (joy1Btn(6) == 1)
		{
			motor [arm] = -50;
		}
		else if (joy1Btn(8) == 1)
		{
			motor [arm] = 50;
		}
		else
		{
			motor [arm] = 0;
		}
	}
}
