#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeft,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     frontRight,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rearLeft,      tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rearRight,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <JoystickDriver.c>

void initializeRobot()
{
}

task main()
{
	initializeRobot();

	int x1, y1, x2;
	int threshold = 8;
	float stdDriveScale = (0.7874 * 0.78);
	int liftPrecisionFactor;

	waitForStart();

	//run loop
	while (1)
	{
		//joystick refresh
		getJoystickSettings(joystick);

		//lift precision factor - manual control of value
		if (joy2Btn(6) == 1) {
			liftPrecisionFactor += 5;
			while (joy2Btn(6) != 0)
			{
			}
		}
		else if (joy2Btn(8) == 1) {
			liftPrecisionFactor -= 5;
			while (joy2Btn(8) != 0)
			{
			}
		}

		//lift precision factor - automatic control of bounds
		if (liftPrecisionFactor <= 0) {
			liftPrecisionFactor = 0;
		}
		else if (liftPrecisionFactor >= 100) {
			liftPrecisionFactor = 100;
		}

		//drive code
	x1 = (abs(joystick.joy1_x1) > threshold) ? joystick.joy1_x1 * stdDriveScale : 0;
	y1 = (abs(joystick.joy1_y1) > threshold) ? joystick.joy1_y1 * stdDriveScale : 0;
	x2 = (abs(joystick.joy1_x2) > threshold) ? joystick.joy1_x2 * stdDriveScale : 0;

		motor [frontLeft] = y1 + x2 + x1;
		motor [frontRight] = y1 - x2 - x1;
		motor [rearLeft] = y1 + x2 - x1;
		motor [rearRight] = y1 - x2 + x1;

		//arm control
		if (joy2Btn(5) == 1) {
			motor [lift] = 100 - liftPrecisionFactor;
		}
		else if (joy2Btn(7) == 1) {
			motor [lift] = -100 + liftPrecisionFactor;
		}
		else {
			motor [lift] = 0;
		}
	}
}
