#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     liftmotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while (1)

{

motor [liftmotor] = (75);
wait10Msec (230);
motor [liftmotor] = (0);
wait10Msec (200);
motor [liftmotor] = (-30);
wait10Msec (150);
motor [liftmotor]= (0);
wait10Msec (200);

}

}
