#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <JoystickDriver.c>

void initializeRobot()
{
}

task main()
{
	int y1, x2;
	int threshold = 10;
	float driveScale = .79;

	initializeRobot();

	while (1) {
		getJoystickSettings(joystick);
	y1 = (abs(joystick.joy1_y1) >= threshold) ? (joystick.joy1_y1 * driveScale) : 0;
	x2 = (abs(joystick.joy1_x2) >= threshold) ? (joystick.joy1_x2 * driveScale) : 0;
		motor [leftDrive] = y1 + x2;
		motor [rightDrive] = y1 - x2;
	}
}
