#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     sonar,          sensorSONAR)
#pragma config(Sensor, S3,     magnetron,      sensorHiTechnicMagnetic)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     frontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rearLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rearRight,     tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//This is a test program for testing the HiTechnic magnetic sensor.

task main ()
{
	while (1)
	{
		nxtDisplayCenteredBigTextLine(3, "%d", SensorValue [magnetron]);
		PlayTone(SensorValue [magnetron], 25 /*50*/);
		wait1Msec(500);
	}
}
