#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     frontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rearLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rearRight,     tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//This is a test program that will be used to test the ability of the LEGO sonar sensor to detect the rolling goals in Cascade Effect.

int abort = 0;
int init = 1;

int x1, y1, x2;

void allStop()
{
	motor [frontLeft] = 0;
	motor [rearLeft] = 0;
	motor [frontRight] = 0;
	motor [rearRight] = 0;
}

void updateMotorSettings()
{
	motor [frontLeft] = y1 + x2 + x1;
	motor [rearLeft] = y1 + x2 - x1;
	motor [frontRight] = y1 - x2 - x1;
	motor [rearRight] = y1 - x2 + x1;
}

int testOne(int action)
{
	x2 = 25;
	updateMotorSettings();
	while (SensorValue [sonar] > 30)
	{
		//waits until the robot is facing an object less than or equal to 30 cm away
	}
	allStop();
	return SensorValue [sonar];
}

task main ()
{
	//nxtDisplayCenteredBigTextLine(3, "%d", testOne(init));
	while (1)
	{
		nxtDisplayCenteredBigTextLine(3, "%d", SensorValue [sonar]);
		wait1Msec(500);
	}
}
