#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     sonarSensor,    sensorSONAR)
#pragma config(Sensor, S3,     irSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     lineFollower,   sensorCOLORFULL)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <JoystickDriver.c>
#include <drivers/hitechnic-irseeker-v2.h>
void initializeRobot ()
{
}

void allStop ()
{
	motor [leftDrive] = 0;
	motor [rightDrive] = 0;
}

void timedDrive (int leftSpeed, int rightSpeed, int driveTime)
{
	ClearTimer(T2);
	while (time1 [T2] < driveTime) {
		motor [leftDrive] = leftSpeed;
		motor [rightDrive] = rightSpeed;
	}
	allStop();
}

void drive (int leftSpeed, int rightSpeed)
{
	motor [leftDrive] = leftSpeed;
	motor [rightDrive] = rightSpeed;
}

void timedRightPointTurn (int turnSpeed, int turnTime)
{
	ClearTimer(T3);
	while (time1 [T3] < turnTime) {
		motor [rightDrive] = -1 * turnSpeed;
		motor [leftDrive] = turnSpeed;
	}
	allStop();
}

void timedLeftPointTurn (int turnSpeed, int turnTime)
{
	ClearTimer(T4);
	while (time1 [T4] < turnTime) {
		motor [rightDrive] = turnSpeed;
		motor [leftDrive] = -1 * turnSpeed;
	}
	allStop();
}

void rightPointTurn (int turnSpeed)
{
	motor [rightDrive] = -1 * turnSpeed;
	motor [leftDrive] = turnSpeed;
}

void leftPointTurn (int turnSpeed)
{
	motor [rightDrive] = turnSpeed;
	motor [leftDrive] = -1 * turnSpeed;
}

task main()
{
	initializeRobot();

#if 0
	waitForStart();
	drive(100, 100, 2500);
	timedRightPointTurn (50, 1100);
	drive(100, 100, 3000);
#endif

	while (1)
	{
		if (SensorValue [irSeeker] > 5) {
			leftPointTurn(50);
		}
		else if (SensorValue [irSeeker] < 5) {
			rightPointTurn(50);
			} else {
			allStop();
		}
		while(SensorValue [sonarSensor] >= 30)
		{
			drive(75, 75);
		}
		allStop();
	}
}
