#pragma config(Sensor, S3,     HTSPB,                sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-superpro.h"

bool HTSPBwriteLED(tSensors link, ubyte mask) {
  memset(HTSPB_I2CRequest, 0, sizeof(tByteArray));

  HTSPB_I2CRequest[0] = 3;                         // Message size
  HTSPB_I2CRequest[1] = HTSPB_I2C_ADDR;             // I2C Address
  HTSPB_I2CRequest[2] = HTSPB_OFFSET + HTSPB_LED; // Start LED read address
  HTSPB_I2CRequest[3] = mask;                      // The specified digital ports


  return writeI2C(link, HTSPB_I2CRequest);
}
const int delay = 250;

task main()
{
  HTSPBsetupIO(HTSPB, 0x3);
#if 1
  while ( true ) {
    int inputRed = HTSPBreadADC(HTSPB, 0, 10);
    int inputBlue = HTSPBreadADC(HTSPB, 1, 10);

    int output = 0x00;

    if ( inputRed > 512 )
    	output |= 0x01;
    if ( inputBlue > 512 )
    	output |= 0x02;

    HTSPBwriteLED( HTSPB, output );
    HTSPBwriteIO( HTSPB, output );

    wait1Msec(50);
  }
#endif
#if 0
	for ( int i = 0; i < 50; i++ ) {
		HTSPBwriteLED(HTSPB, 0x01);
    HTSPBwriteIO(HTSPB, 0x01);
		wait1Msec(delay);
		HTSPBwriteLED(HTSPB, 0x02);
    HTSPBwriteIO(HTSPB, 0x02);
		wait1Msec(delay);
		HTSPBwriteLED(HTSPB, 0x00);
    HTSPBwriteIO(HTSPB, 0x00);
		wait1Msec(delay);
	}
#endif
}
