#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     test,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <JoystickDriver.c>

task main()
{
	bDisplayDiagnostics = false;
	eraseDisplay();
	ClearTimer(T1);
	nxtDisplayCenteredBigTextLine(3, "ROT +");
	while (time1[T1] < 1000)
	{
		motor [test] = 100;
	}
	motor [test] = 0;
	wait1Msec(500);
	ClearTimer(T1);
	nxtDisplayCenteredBigTextLine(3, "ROT -");
	while (time1[T1] < 1000)
	{
		motor [test] = -100;
	}
	motor [test] = 0;
	wait1Msec(500);
	nxtDisplayCenteredBigTextLine(3, "PWR ++");
	for (int i = 5; i < 100; i+=5)
	{
		motor [test] = i;
		wait1Msec(250);
	}
	motor [test] = 0;
	wait1Msec(500);
	nxtDisplayCenteredBigTextLine(3, "PWR --");
	for (int i = -5; i > -100; i-=5)
	{
		motor [test] = i;
		wait1Msec(250);
	}
	motor [test] = 0;
	eraseDisplay();
}
