#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     testMotor,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include <JoystickDriver.c>

task main()
{
	while (1)
	{
		if (joy1Btn(6) == 1)
		{
			motor [testMotor] = 10;
		}
		else if (joy1Btn(5) == 1)
		{
			motor [testMotor] = -10;
			} else {
			motor [testMotor] = 0;
		}
	}
}
