#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     theMotor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <JoystickDriver.c>

task main()
{
int threshold = 6;
	while (true)
	{
		getJoystickSettings(joystick);
		/*if (joy1Btn(5) == 1)
			motor [theMotor] = 100;
		else if (joy1Btn(7) == 1)
			motor [theMotor] = -100;
		else
			motor [theMotor] = 0;*/
			motor [theMotor] = abs(joystick.joy1_y1) > threshold ? (joystick.joy1_y1 * 0.5) : 0;
	}
}
