#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <JoystickDriver.c>

task main()
{
	const int t = 8;
	while (1)
	{
		getJoystickSettings(joystick);
		motor [leftDrive] = (abs(joystick.joy1_y1) > t) ? joystick.joy1_y1 : 0;
		motor [rightDrive] = (abs(joystick.joy1_y2) > t) ? joystick.joy1_y2 : 0;
	}
}
