#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightHarvester, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftHarvester, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightDrive,    tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <JoystickDriver.c>

const int threshold = 12;

task main ()
{
	while (1)
	{
		getJoystickSettings(joystick);
	motor [leftDrive] = abs(joystick.joy1_y1) > threshold ? joystick.joy1_y1 : 0;
	motor [rightDrive] = abs(joystick.joy1_y2) > threshold ? joystick.joy1_y2 : 0;

		if (joy1Btn(6) == 1)
		{
			motor [leftHarvester] = 100;
			motor [rightHarvester] = 100;
		}
		else if (joy1Btn(5) == 1)
		{
			motor [leftHarvester] = -100;
			motor [rightHarvester] = -100;
			} else {
			motor [rightHarvester] = 0;
			motor [leftHarvester] = 0;
		}
	}
}
