#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     sonar,          sensorSONAR)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rearLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     harvester,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     rearRight,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C1_2,     frontRight,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C2_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    guiderDrop,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    leftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    rightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    pivot,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    doors,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <JoystickDriver.c>
#include "Cascade_Functions.h"

task main()
{
	driveCycles = 6;
	humor = 120;
	bDisplayDiagnostics = false;
	initializeAutonomous();
	bDisplayDiagnostics = true;
	waitForStart();
	motor [lift] = 100;
	wait1Msec(750);
	motor [lift] = 0;
	wait1Msec(250);
	//#if 0
	while (nMotorEncoder [frontLeft] > -(driveCycles * driveEncoderCycle))
	{
		drive(0, -25, 0);
	}
	while (SensorValue [sonar] > 50)
	{
		drive(0, 0, 25);
	}
	wait1Msec(655);
	allStop();
	StartTask(failSafe);
	while (SensorValue [sonar] > 20)
	{
		drive(0, -20, 0);
	}
	StopTask(failSafe);
	//#endif
	wait1Msec(500);
	allStop();
	servo [leftHook] = 168;
	servo [rightHook] = 16;
	wait1Msec(100);
	score(60);

	servo [doors] = 122;
	wait1Msec(250);
	servo [doors] = 140;
	wait1Msec(250);
	servo [doors] = 150;
	wait1Msec(250);
	servo [doors] = 160;
	wait1Msec(250);
	servo [doors] = 122;
	wait1Msec(50);
	//#if 0
	drive(0, 0, -90);
	wait1Msec(1300);
	allStop();
	nMotorEncoder [frontLeft] = 0;
	while (nMotorEncoder [frontLeft] > -0.8 * driveEncoderCycle)
	{
		drive(0, -100, 0);
	}
	allStop();
	servo [leftHook] = 35;
	servo [rightHook] = 140;
	wait1Msec(250);
	while (nMotorEncoder [frontLeft] < -0.55 * driveEncoderCycle)
	{
		drive(0, 100, 0);
	}
	while (nMotorEncoder [frontLeft] < -0.1 * driveEncoderCycle)
	{
		drive(0, 50, 0);
	}
	allStop();
	drive(0, 0, 50);
	wait1Msec(700);
	drive(0, -50, 0);
	wait1Msec(700);
	while (SensorValue [sonar] > 45)
	{
		drive(0, 0, -25);
	}
	wait1Msec(550);
	allStop();
	//ClearTimer(T3);
	//motor [lift] = 100;
	//while (time1[T3] < 1500)
	//{
	//}
	//motor [lift] = 0;
	StartTask(failSafe);
	while (SensorValue [sonar] > 20)
	{
		drive(0, -20, 0);
	}
	StopTask(failSafe);
	wait1Msec(250);
	allStop();
	servo [leftHook] = 168;
	servo [rightHook] = 16;
	score(30);
	ClearTimer(T3);
	while (time1[T3] < 2000)
	{
		drive(0, 100, 0);
	}
	allStop();
	//#endif
}
