#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rearLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     rearRight,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C1_2,     frontRight,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C2_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    guiderDrop,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    leftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    rightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    cover,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <JoystickDriver.c>

int driveEncoderCycle = 1120;
int driveCycles = 5;
int humor = 80;

void drive(int x1, int y1, int x2)
{
	motor [frontLeft] = (y1 + x2 + x1);
	motor [frontRight] = (y1 - x2 - x1);
	motor [rearLeft] = (y1 + x2 - x1);
	motor [rearRight] = (y1 - x2 + x1);
}

void allStop()
{
	drive(0, 0, 0);
}

int resetDriveEncoders()
{
	nMotorEncoder [frontLeft] = 0;
	nMotorEncoder [frontRight] = 0;
	nMotorEncoder [rearLeft] = 0;
	nMotorEncoder [rearRight] = 0;
	return 0;
}

void updateDriveCyclesDisplay()
{
	nxtDisplayCenteredTextLine(3, "Rotations: %d", driveCycles);
}

void updateHumorDisplay()
{
	nxtDisplayCenteredTextLine(3, "Set humor: %d%%", humor);
}

void initializeRobot()
{
	nxtDisplayCenteredTextLine(3, "Initializaing");
	nxtDisplayCenteredTextLine(4, "servos...");
	servo [cover] = 160;
	servo [leftHook] = 35;
	servo [rightHook] = 140;
	wait1Msec(1000);
	eraseDisplay();
	if (resetDriveEncoders() == 0)
	{
		nxtDisplayCenteredTextLine(3, "Encoders");
		nxtDisplayCenteredTextLine(4, "successfully");
		nxtDisplayCenteredTextLine(5, "reset.");
		wait1Msec(1000);
	}
	eraseDisplay();
	updateDriveCyclesDisplay();
	while (1)
	{
		if (nNxtButtonPressed == 1)
		{
			while (nNxtButtonPressed != -1)
			{
			}
			driveCycles ++;
			updateDriveCyclesDisplay();
		}
		else if (nNxtButtonPressed == 2)
		{
			while (nNxtButtonPressed != -1)
			{
			}
			driveCycles --;
			updateDriveCyclesDisplay();
		}
		if (nNxtButtonPressed == 3)
		{
			while (nNxtButtonPressed != -1)
			{
			}
			eraseDisplay();
			if (driveCycles > 1)
				nxtDisplayCenteredTextLine(3, "%d rotations", driveCycles);
			else if (driveCycles == 1)
				nxtDisplayCenteredTextLine(3, "%d rotation", driveCycles);
			wait1Msec(800);
			break;
		}
		if (driveCycles < 0)
		{
			driveCycles = 0;
			updateDriveCyclesDisplay();
		}
	}
	updateHumorDisplay();
	while (1)
	{
		if (nNxtButtonPressed == 1)
		{
			while (nNxtButtonPressed != -1)
			{
			}
			humor += 10;
			updateHumorDisplay();
		}
		else if (nNxtButtonPressed == 2)
		{
			while (nNxtButtonPressed != -1)
			{
			}
			humor -= 10;
			updateHumorDisplay();
		}
		if (nNxtButtonPressed == 3)
		{
			while (nNxtButtonPressed != -1)
			{
			}
			eraseDisplay();
			nxtDisplayCenteredTextLine(3, "%d%% humor", humor);
			wait1Msec(800);
			break;
		}
		if (humor < 0)
		{
			humor = 0;
			updateHumorDisplay();
		}
		if (humor > 100)
		{
			humor = 100;
			updateHumorDisplay();
		}
	}
}

task failSafe()
{
	ClearTimer(T1);
	while(1)
	{
		if (time1 [T1] > 3500)
		{
			StopAllTasks();
		}
	}
}

task main ()
{
	bDisplayDiagnostics = false;
	initializeRobot();
	bDisplayDiagnostics = true;
	waitForStart();
	while (nMotorEncoder [frontRight] > -(driveCycles * driveEncoderCycle))
	{
		drive(0, -25, 0);
	}
	while (SensorValue [sonar] > 50)
	{
		drive(0, 0, 25);
	}
	wait1Msec(350);
	allStop();
	StartTask(failSafe);
	while (SensorValue [sonar] > 20)
	{
		drive(0, -20, 0);
	}
	StopTask(failSafe);
	wait1Msec(500);
	allStop();
	servo [leftHook] = 168;
	servo [rightHook] = 16;
	wait1Msec(250);
	motor [lift] = 100;
	wait1Msec(1500);
	motor [lift] = 0;
	wait1Msec(500);
	motor [arm] = -100;
	wait1Msec(2250);
	motor [arm] = 0;
	wait1Msec(500);
	servo [cover] = 12;
	wait1Msec(750);
	servo [cover] = 160;
	wait1Msec(250);
	motor [arm] = 100;
	wait1Msec(2000);
	motor [arm] = 0;
	wait1Msec(250);
	motor [lift] = -100;
	wait1Msec(800);
	motor [lift] = 0;
	wait1Msec(500);
	drive(0, 0, -25);
	wait1Msec(725);
	allStop();
	wait1Msec(250);
	drive(100, 0, 0);
	wait1Msec(1700);
	drive(0, 100, 0);
	wait1Msec(3400);
	allStop();
	wait1Msec(250);
	drive(0, 0, 50);
	wait1Msec(800);
	allStop();
	drive(0, 75, 0);
	wait1Msec(750);
	allStop();
	wait1Msec(250);
	drive(-75, 0, 0);
	wait1Msec(1500);
	allStop();
}
