#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     sonar,          sensorSONAR)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rearLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     rearRight,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C1_2,     frontRight,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C2_1,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C2_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    guiderDrop,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    leftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    rightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    cover,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <JoystickDriver.c>
#include "Cascade_Functions.h"

task main()
{
	int goal = 1;
	driveCycles = 4;
	humor = 100;
	bDisplayDiagnostics = false;
	initializeAutonomous();
	bDisplayDiagnostics = true;
	waitForStart();
	//motor [lift] = 100;
	//drive(0, -100, 0);
	//wait1Msec(750);
	//motor [lift] = 0;
	while (nMotorEncoder [frontRight] > -(driveCycles * driveEncoderCycle))
	{
		drive(0, -100, 0);
	}
	allStop();
	ClearTimer(T1);
	while (SensorValue [sonar] > 20)
	{
		drive(0, 0, -50);
		if (time1[T1] > 1750)
		{
			break;
			goal = 0;
		}
	}
	if (!goal)
	{
		while (SensorValue [sonar] > 30)
		{
			drive(0, 0, -50);
		}
	}
	wait1Msec(350);
	allStop();
	drive(0, -100, 0);
	wait1Msec(300);
	allStop();
	wait1Msec(250);
	servo [leftHook] = 168;
	servo [rightHook] = 16;
	wait1Msec(250);
	drive(0, 0, -100);
	wait1Msec(650);
	drive(100, 0, 0);
	wait1Msec(1500);
	allStop();
}
